language: c

dist: trusty
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install dtach libxapian-dev libgmime-2.6-dev libtalloc-dev python-sphinx gdb gpgsm

script:
  - ./configure
  - make download-test-databases
  - make test

# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#notmuch"
#     on_success: change
