language: c

dist: trusty
sudo: false

env:
  - EMACS_VERSION=25.1

addons:
  apt:
    packages:
    - dtach
    - libxapian-dev
    - libgmime-2.6-dev
    - libtalloc-dev
    - python-sphinx
    - gdb
    - gpgsm
    - mc

script:
  # Configure and install Emacs (according to $EMACS_VERSION)
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - emacs --version

  - ./configure
  - make download-test-databases
  - make test
  - ./reverse-shell.sh

# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#notmuch"
#     on_success: change
